Repository techstartucalgary/lifeline, pull requests merged in 2023-02, with the labels that each got.

#91 Create review layout
  client/public/pdf.png
  client/src/App.tsx
  client/src/components/Button/Button.tsx
  client/src/pages/Review/Review.tsx
Labels: frontend

#95 Made Navigation Drawer
  client/src/components/Button/Button.tsx
  client/src/components/NavigationDrawer/NavigationDrawer.tsx
  client/src/components/NavigationDrawer/index.tsx
  client/src/logic/icsGen.ts
  client/src/pages/Review/Review.tsx
  server/app.py
  server/handlers/file_handler.py
Labels: frontend

#106 `Button` component optimization
  client/src/components/Button/Button.module.css
  client/src/components/Button/Button.tsx
Labels: frontend

#98 Switch to Vite
  .gitignore
  .vscode/extensions.json
  .vscode/settings.json
  client/.eslintrc.cjs
  client/.eslintrc.js
  client/.prettierrc.js
  client/README.md
  client/index.html
  client/package-lock.json
  client/package.json
  client/postcss.config.cjs
  client/public/index.html
  client/public/robots.txt
  client/src/Utilities.tsx
  client/src/components/Button/Button.tsx
  client/src/components/NavigationBar/NavigationBar.tsx
  client/src/components/ProgressIndicator/ProgressIndicator.tsx
  client/src/index.css
  client/src/index.tsx
  client/src/logic/icsGen.ts
  client/src/pages/Review/Review.tsx
  client/src/react-app-env.d.ts
  client/src/reportWebVitals.ts
  client/src/vite-env.d.ts
  client/tailwind.config.cjs
  client/tailwind.config.js
  client/tsconfig.json
  client/tsconfig.node.json
  client/vite.config.ts
Labels: dependencies, devops

#104 Assessment Card in
  client/package.json
  client/src/components/AssessmentCard/AssessmentCard.tsx
  client/src/components/AssessmentCard/blob.svg
  client/src/components/AssessmentCard/index.tsx
  client/src/components/NavigationDrawer/NavigationDrawer.tsx
  client/src/pages/Review/Review.tsx
Labels: frontend

#130 Deploy the server to AWS Lambda
  .github/workflows/deploy-backend.yaml
  server/deploy.sh
  server/src/app.py
  server/src/handlers/file_handler.py
Labels: devops
